# Change this to re-enable the workflow.
name: Github Sosad Checkin

on:
  push:
    branches:
      - master
  schedule:
    - cron: "0 1 * * *"
  workflow_dispatch: # enable manual

jobs:
  build:
    runs-on: ubuntu-latest
 #if: github.event.repository.owner.id == github.event.sender.id
    # https://p3terx.com/archives/github-actions-manual-trigger.html

    steps:
      - name: Checkout codes
        uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
      - name: Install dependencies
        run: npm install
      - run: node index.js

        env:
          botToken: ${{ secrets.botToken }}
          chatID: ${{ secrets.chatID }}
          sosad_cookie: ${{ secrets.sosad_cookie }}
    # https://p3terx.com/archives/github-actions-manual-trigger.html
      - uses: actions/checkout@v4

      - name: Update anime list
        uses: ycs77/readme-anime-list@main
        with:
          target: 'README.md'
          template: 'template/README-eta.md'
          bangumi_username: 'ryanlo713'
          bangumi_limit: 10
          user_agent: 'ryanlo713/Sosad_checkin README'

      - name: Commit
        uses: EndBug/add-and-commit@v9
        with:
          message: 'Update generated README'
